- src: https://github.com/CSCfi/ansible-role-puppetmaster.git
  path: roles
  version: cccp_branch_inject

- src: https://github.com/CSCfi/ansible-role-puppetize.git
  path: roles

- src: https://github.com/junousi/ansible-openldap_server.git
  name: ansible-role-openldap-server
  path: roles
  version: simpleusertemplate

- src: https://github.com/CSCfi/ansible-role-squid.git
  path: roles

- src: https://github.com/CSCfi/ansible-role-rally.git
  path: roles
  version: polte

- src: https://github.com/CSCfi/ansible-role-rally-scenarios.git
  path: roles
  version: polte
