---
ansible_ssh_common_args: "-i {{ ansible_ssh_private_key_file }} -o ProxyCommand='ssh -i {{ ansible_ssh_private_key_file }} -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -W %h:%p -q {{ vm_user_account }}@{{ hostvars['puppet-node']['ansible_ssh_host'] }}'"
polte_ss_ca_cert: |
  -----BEGIN CERTIFICATE-----
  MIIF1zCCA7+gAwIBAgIJAJJEPzN8L+uPMA0GCSqGSIb3DQEBCwUAMIGBMQswCQYD
  VQQGEwJGSTEQMA4GA1UECAwHVXVzaW1hYTEOMAwGA1UEBwwFRXNwb28xDDAKBgNV
  BAoMA0NTQzENMAsGA1UECwwEQ0NEQjELMAkGA1UEAwwCQ0ExJjAkBgkqhkiG9w0B
  CQEWF2p1a2thLm5vdXNpYWluZW5AY3NjLmZpMB4XDTIwMDQwNTExNTY1OFoXDTIz
  MDEyNDExNTY1OFowgYExCzAJBgNVBAYTAkZJMRAwDgYDVQQIDAdVdXNpbWFhMQ4w
  DAYDVQQHDAVFc3BvbzEMMAoGA1UECgwDQ1NDMQ0wCwYDVQQLDARDQ0RCMQswCQYD
  VQQDDAJDQTEmMCQGCSqGSIb3DQEJARYXanVra2Eubm91c2lhaW5lbkBjc2MuZmkw
  ggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDaHVIllnMYkuDayowzut2S
  wJr+w+PM34NNGODZSgTsQ5ff52EtLWOCsa6D94SHU76KQnx1WhvEM6avrGFPnUDk
  TFnuG+3rEOhXZ4wgioudERErjVUT1YlmpU8YkXMOWkHZtjxej7D14PSrYal/GBBF
  FWHeZ1nnY/nQ9sMRlwYOPNQ+f2JvLD04x7Wresr01uPapacFmh+GjedTU9y5aNt5
  yP/0F6ra8pGKq9lQpETkSgY4SK92mUfSCnRamzlugRZKyHXEcQ/w+v+fOGpTEBmd
  Y6TpLqQFoUv0zt9BD/lFc75omIt69sEzY58CMqX0Hek6ywHI+w1FQ2nFvH5jEzpi
  yGsC+CJD9EWV04WQYMFNPA2priIm50jZM+DObnXN2OgxhSyYakKMFunOBaUITm5q
  kMPg/hcPTLsewpTvL2cDJhSa634JwTOq1qHn2U6GlzZAF6Xj/Z4rBfaID6FHNOO+
  pbNp0QKOpJPd838t1SYjfoG23ZmbAr8osm7t3qBJoVw34Y8kSTQM+uVmbNlFiyVV
  B3rOoxnI3//I97xXmHl7WFDMvNmF+iGXeV1w+y2LddMvUl82HJHltnXKktU9zzG/
  pSdHZ1v5sIVxbOmcLmI69uyEC0DMjNVvwGy0/w7v8/1sZ4TAMJlelAiOVaRlsu+8
  13XvzEC7Gtlm6g43anyj7wIDAQABo1AwTjAdBgNVHQ4EFgQULDoHU0H1R1JS8B+8
  2R2Sqgza8wswHwYDVR0jBBgwFoAULDoHU0H1R1JS8B+82R2Sqgza8wswDAYDVR0T
  BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAgEADKx3xneTyw0UFzsb09RpufrAgeWe
  dIuQsKaCFPKHy77eGjL4qrNvZI72cmwlpyb5wpoz0FJd8QB5lQfaIBWAvI9R5SP7
  YinZUTgAr6dnFEm54mRYikXu1PmakXvEc1f3tP1Ept8EOjs4BpYiCyE9UarV0+lw
  itdJsLteGaK9w2uXmBDVdWkHpHW7T65h97OWTCmqKyOxIy/JT4YIS2LFh7/5zNi0
  fFnMV5x7p7efpWNKAY9h+3KCP/CzBBOqXIqFDMwrv5vO3UvPzM2DY1YwECSo47ye
  OwN0inNeYRYq67w0rH2NVVFoDlHBlG+zdyIsuHTKGLsHV0kq0CKnEPbHJY91jShu
  VQ9sSZOTK6WdHdHq6k0nLGCyhwrkfFR1jJ6xo6hrcaVzfRrtF7zclf6DQwCy/MsF
  lb8S++ChHPOF90+aGzBKU+gHms27Mb7MrNLz6raXKcLYIFwR0r6PFxRr9ut194PR
  J06C6uGANMKqpGad+aNrbsUxLut89/dIGHMSaZVu/9XCNS21M99aHmRP2tmZflVH
  OwUbDCoTPOyKLByTT9E4Dh6uj6DlzKyipZcPshyYVtELS7F76u8CRaLljoaHQ1eV
  /sU8CnBj2hQZ5FHQaxVLipQ1UGayO6LdPS70Gph50vFJq6OOUgWs7Z6L5y/r/WSS
  ibwI/jZVkaYw3gI=
  -----END CERTIFICATE-----
proxy_env:
