heat_template_version: 2016-10-14

description: >
  Build machines for deployment of OpenStack.

parameters:
  index:
    type: number
  ssh_key_name:
    description: The name of the SSH key in OpenStack to add to hosts.
    type: string
  ceph_mon_node_flavor:
    description: The flavor to use for the VMs running OpenStack object nodes.
    type: string
  ceph_mon_node_image:
    description: The image to use for the VMs running OpenStack object nodes.
    type: string
  mgmt_network_name:
    description: The network to use for the VMs.
    type: string
  ceph_mon_node_names:
    type: comma_delimited_list
  ooo_mon_secgroup:
    type: string
  cloud_init_nameservers:
    type: comma_delimited_list
    description: The nameservers to configure via cloud-init.

resources:
  obj_node:
    type: OS::Nova::Server
    properties:
      flavor: { get_param: ceph_mon_node_flavor }
      image: { get_param: ceph_mon_node_image }
      key_name: { get_param: ssh_key_name }
      security_groups:
        -  { get_param: ooo_mon_secgroup }
      name: { get_param: [ceph_mon_node_names, {get_param: index}] }
      networks:
        - network: { get_param: mgmt_network_name }
      metadata: { 'ansible_group': 'cephmon' }
      user_data_format: RAW
      user_data:
        str_replace:
          params:
            $hostname: { get_param: [ceph_mon_node_names, {get_param: index}] }
            $nameservers: { get_param: cloud_init_nameservers }
          template: { get_file: user-data-generic.yaml }

outputs:
  show:
    value: {get_attr: [obj_node, show]}
