---
# Build a heat stack. Generate an inventory file based on a
# successfully created stack.

- hosts: localhost
  gather_facts: no
  tasks:
    - name: Check if inventory file has been created
      local_action: stat path="../inventory/ooo_inventory"
      register: ooo_inventory_file

    - name: End play if inventory exists
      meta: end_play
      when: ooo_inventory_file.stat.exists

    - name: Build a Heat stack for OpenStack
      register: heat_stack
      os_stack:
        name: "{{ heat_stack_name }}"
        state: present
        template: "../files/ooo-heat-stack.yml"
        environment:
          - "{{ heat_environment_file }}"
        parameters:
          ceph_mon_node_image: "CentOS-8.3.2011-upstream"
          ceph_osd_node_image: "CentOS-8.3.2011-upstream"
          ceph_mgr_node_image: "CentOS-8.3.2011-upstream"

    # In the next task, addresses[0] or addresses.0 did not
    # work for some reason.
    - debug: msg="{{ heat_stack.stack.outputs[0].output_value[0].addresses.keys()[0] }}"
      register: magic_index_network

    - name: Add Ceph mon nodes to inventory
      add_host:
        name: "{{ item.name }}"
        groups: "{{ item.metadata.ansible_group }}"
        ansible_ssh_host: "{{ item.addresses[magic_index_network.msg][0].addr }}"
        ansible_ssh_user: "{{ vm_user_account }}"
      no_log: yes
      with_items:
        - "{{ heat_stack.stack.outputs[0].output_value }}"
        - "{{ heat_stack.stack.outputs[1].output_value }}"
        - "{{ heat_stack.stack.outputs[2].output_value }}"
#        - "{{ heat_stack.stack.outputs[3].output_value }}"
#        - "{{ heat_stack.stack.outputs[4].output_value }}"
#        - "{{ heat_stack.stack.outputs[5].output_value }}"
#        - "{{ heat_stack.stack.outputs[6].output_value }}"
#        - "{{ heat_stack.stack.outputs[7].output_value }}"
#        - "{{ heat_stack.stack.outputs[8].output_value }}"
      when: item.metadata is defined and item.metadata.ansible_group == "cephmon"

    - name: Add Ceph osd nodes to inventory
      add_host:
        name: "{{ item.name }}"
        groups: "{{ item.metadata.ansible_group }}"
        ansible_ssh_host: "{{ item.addresses[magic_index_network.msg][0].addr }}"
        ansible_ssh_user: "{{ vm_user_account }}"
      no_log: yes
      with_items:
        - "{{ heat_stack.stack.outputs[0].output_value }}"
        - "{{ heat_stack.stack.outputs[1].output_value }}"
        - "{{ heat_stack.stack.outputs[2].output_value }}"
#        - "{{ heat_stack.stack.outputs[3].output_value }}"
#        - "{{ heat_stack.stack.outputs[4].output_value }}"
#        - "{{ heat_stack.stack.outputs[5].output_value }}"
#        - "{{ heat_stack.stack.outputs[6].output_value }}"
#        - "{{ heat_stack.stack.outputs[7].output_value }}"
#        - "{{ heat_stack.stack.outputs[8].output_value }}"
      when: item.metadata is defined and item.metadata.ansible_group == "cephosd"

    - name: Add puppet node to inventory
      add_host:
        name: "{{ item.name }}"
        groups: "{{ item.metadata.ansible_group }}"
        ansible_ssh_host: "{{ item.addresses[magic_index_network.msg][1].addr }}"
        ansible_ssh_user: "{{ vm_user_account }}"
      no_log: yes
      with_items:
        - "{{ heat_stack.stack.outputs[0].output_value }}"
        - "{{ heat_stack.stack.outputs[1].output_value }}"
        - "{{ heat_stack.stack.outputs[2].output_value }}"
#        - "{{ heat_stack.stack.outputs[3].output_value }}"
#        - "{{ heat_stack.stack.outputs[4].output_value }}"
#        - "{{ heat_stack.stack.outputs[5].output_value }}"
#        - "{{ heat_stack.stack.outputs[6].output_value }}"
#        - "{{ heat_stack.stack.outputs[7].output_value }}"
#        - "{{ heat_stack.stack.outputs[8].output_value }}"
      when: item.metadata is defined and item.metadata.ansible_group == "puppet"

    - name: Generate an inventory file
      template: src=templates/ooo_inventory.j2 dest="../inventory/ooo_inventory"
