---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Check if inventory file has been created
      local_action: stat path="../inventory/ooo_inventory"
      register: ooo_inventory_file

    - name: End play if inventory exists
      meta: end_play
      when: ooo_inventory_file.stat.exists

    - name: Build a Heat stack for OpenStack
      register: heat_stack
      os_stack:
        name: "{{ heat_stack_name }}"
        state: present
        template: "../files/ooo-heat-stack.yml"
        environment:
          - "{{ heat_environment_file }}"

    - debug: msg="{{ heat_stack.stack.outputs[0].output_value[0].addresses.keys()[0] }}"
      register: magic_index_network

    - name: Add Galera nodes to inventory
      add_host:
        name: "{{ item.name }}"
        groups: "{{ item.metadata.ansible_group }}"
        ansible_ssh_host: "{{ item.addresses[magic_index_network.msg][0].addr }}"
        ansible_ssh_user: "{{ vm_user_account }}"
      no_log: yes
      with_items:
        - "{{ heat_stack.stack.outputs[0].output_value }}"
        - "{{ heat_stack.stack.outputs[1].output_value }}"
        - "{{ heat_stack.stack.outputs[2].output_value }}"
        - "{{ heat_stack.stack.outputs[3].output_value }}"
        - "{{ heat_stack.stack.outputs[4].output_value }}"
        - "{{ heat_stack.stack.outputs[5].output_value }}"
        - "{{ heat_stack.stack.outputs[6].output_value }}"
      when: item.metadata.ansible_group == "galera"

    - name: Add api nodes to inventory
      add_host:
        name: "{{ item.name }}"
        groups: "{{ item.metadata.ansible_group }}"
        ansible_ssh_host: "{{ item.addresses[magic_index_network.msg][0].addr }}"
        ansible_ssh_user: "{{ vm_user_account }}"
      no_log: yes
      with_items:
        - "{{ heat_stack.stack.outputs[0].output_value }}"
        - "{{ heat_stack.stack.outputs[1].output_value }}"
        - "{{ heat_stack.stack.outputs[2].output_value }}"
        - "{{ heat_stack.stack.outputs[3].output_value }}"
        - "{{ heat_stack.stack.outputs[4].output_value }}"
        - "{{ heat_stack.stack.outputs[5].output_value }}"
        - "{{ heat_stack.stack.outputs[6].output_value }}"
      when: item.metadata.ansible_group == "api"

    - name: Add obj nodes to inventory
      add_host:
        name: "{{ item.name }}"
        groups: "{{ item.metadata.ansible_group }}"
        ansible_ssh_host: "{{ item.addresses[magic_index_network.msg][0].addr }}"
        ansible_ssh_user: "{{ vm_user_account }}"
      no_log: yes
      with_items:
        - "{{ heat_stack.stack.outputs[0].output_value }}"
        - "{{ heat_stack.stack.outputs[1].output_value }}"
        - "{{ heat_stack.stack.outputs[2].output_value }}"
        - "{{ heat_stack.stack.outputs[3].output_value }}"
        - "{{ heat_stack.stack.outputs[4].output_value }}"
        - "{{ heat_stack.stack.outputs[5].output_value }}"
        - "{{ heat_stack.stack.outputs[6].output_value }}"
      when: item.metadata.ansible_group == "obj"

    - name: Add Ceph mon nodes to inventory
      add_host:
        name: "{{ item.name }}"
        groups: "{{ item.metadata.ansible_group }}"
        ansible_ssh_host: "{{ item.addresses[magic_index_network.msg][0].addr }}"
        ansible_ssh_user: "{{ vm_user_account }}"
      no_log: yes
      with_items:
        - "{{ heat_stack.stack.outputs[0].output_value }}"
        - "{{ heat_stack.stack.outputs[1].output_value }}"
        - "{{ heat_stack.stack.outputs[2].output_value }}"
        - "{{ heat_stack.stack.outputs[3].output_value }}"
        - "{{ heat_stack.stack.outputs[4].output_value }}"
        - "{{ heat_stack.stack.outputs[5].output_value }}"
        - "{{ heat_stack.stack.outputs[6].output_value }}"
      when: item.metadata.ansible_group == "cephmon"

    - name: Add Ceph osd nodes to inventory
      add_host:
        name: "{{ item.name }}"
        groups: "{{ item.metadata.ansible_group }}"
        ansible_ssh_host: "{{ item.addresses[magic_index_network.msg][0].addr }}"
        ansible_ssh_user: "{{ vm_user_account }}"
      no_log: yes
      with_items:
        - "{{ heat_stack.stack.outputs[0].output_value }}"
        - "{{ heat_stack.stack.outputs[1].output_value }}"
        - "{{ heat_stack.stack.outputs[2].output_value }}"
        - "{{ heat_stack.stack.outputs[3].output_value }}"
        - "{{ heat_stack.stack.outputs[4].output_value }}"
        - "{{ heat_stack.stack.outputs[5].output_value }}"
        - "{{ heat_stack.stack.outputs[6].output_value }}"
      when: item.metadata.ansible_group == "cephosd"

    - name: Add puppet node to inventory
      add_host:
        name: "{{ item.name }}"
        groups: "{{ item.metadata.ansible_group }}"
        ansible_ssh_host: "{{ item.addresses[magic_index_network.msg][1].addr }}"
        ansible_ssh_user: "{{ vm_user_account }}"
      no_log: yes
      with_items:
        - "{{ heat_stack.stack.outputs[0].output_value }}"
        - "{{ heat_stack.stack.outputs[1].output_value }}"
        - "{{ heat_stack.stack.outputs[2].output_value }}"
        - "{{ heat_stack.stack.outputs[3].output_value }}"
        - "{{ heat_stack.stack.outputs[4].output_value }}"
        - "{{ heat_stack.stack.outputs[5].output_value }}"
        - "{{ heat_stack.stack.outputs[6].output_value }}"
      when: item.metadata.ansible_group == "puppet"

    - name: Add LDAP node to inventory
      add_host:
        name: "{{ item.name }}"
        groups: "{{ item.metadata.ansible_group }}"
        ansible_ssh_host: "{{ item.addresses[magic_index_network.msg][0].addr }}"
        ansible_ssh_user: "{{ vm_user_account }}"
      no_log: yes
      with_items:
        - "{{ heat_stack.stack.outputs[0].output_value }}"
        - "{{ heat_stack.stack.outputs[1].output_value }}"
        - "{{ heat_stack.stack.outputs[2].output_value }}"
        - "{{ heat_stack.stack.outputs[3].output_value }}"
        - "{{ heat_stack.stack.outputs[4].output_value }}"
        - "{{ heat_stack.stack.outputs[5].output_value }}"
        - "{{ heat_stack.stack.outputs[6].output_value }}"
      when: item.metadata.ansible_group == "ldap"

    - name: Generate an inventory file
      template: src=templates/ooo_inventory.j2 dest="../inventory/ooo_inventory"
