---
# Post puppetization API node modifications.

- hosts: api
  become: yes
  become_user: root
  tasks:
    - name: Disable Horizon to keystone SSL verification
      lineinfile:
        path: /etc/openstack-dashboard/local_settings
        regexp: '.*OPENSTACK_SSL_NO_VERIFY.*'
        line: 'OPENSTACK_SSL_NO_VERIFY = True'
    - name: Relax Horizon allowed hosts
      shell: sed -i "s/^ALLOWED_HOSTS.*/ALLOWED_HOSTS = ['*', ]/" /etc/openstack-dashboard/local_settings
    - name: Change Horizon login backend to ldap
      shell: sed -i 's/native/ldap/' /etc/openstack-dashboard/local_settings
