---
# Workarounds for both api nodes
- hosts: api
  become: true
  become_user: root
  pre_tasks:
# workaround: pip provider fails
    - shell: ln -s /usr/bin/pip /usr/bin/pip-python
      args:
        creates: /usr/bin/pip-python
# workaround: Add admin role outside of puppet code
    - cron:
        name: Add admin role to service group
        user: root
        job: source /root/openrc.admintoken;openstack role add --project service --group service admin
# workaround: preinstall openstack CLI
    - yum:
        name: centos-release-openstack-newton
        state: present
    - yum:
        name: python-openstackclient
        state: present
    - name: use insecure in all /bin/openstack calls due to self-signed cert
      lineinfile:
        path: /bin/openstack
        insertafter: import\ sys
        line: "sys.argv.append('--insecure')"
      ignore_errors: true
    - meta: clear_host_errors
