---
# This playbook contains API node modifications that
# should be done before puppetizing.

- hosts: api
  become: true
  become_user: root
  pre_tasks:
# workaround: pip provider fails
    - name: Workaround pip provider failure
      shell: ln -s /usr/bin/pip /usr/bin/pip-python
      args:
        creates: /usr/bin/pip-python
# workaround: Preinstall openstack CLI
    - name: Preinstall openstack CLI - Newton repo
      yum:
        name: centos-release-openstack-newton
        state: present
    - name: Preinstall openstack CLI
      yum:
        name: python-openstackclient
        state: present
    - name: Use insecure in all /bin/openstack calls due to self-signed cert
      lineinfile:
        path: /bin/openstack
        insertafter: import\ sys
        line: "sys.argv.append('--insecure')"
