---
# This playbook contains API node modifications that
# should be done before puppetizing.

- hosts: api
  become: true
  become_user: root
  pre_tasks:
# workaround: pip provider fails
    - name: Workaround pip provider failure
      shell: ln -s /usr/bin/pip /usr/bin/pip-python
      args:
        creates: /usr/bin/pip-python
