---
# Workarounds for both api nodes
- hosts: api
  become: true
  become_user: root
  pre_tasks:
# workaround: SELinux blocks rabbitmq HiPE compilation and httpd
    - shell: sed -i 's/^SELINUX=.*/SELINUX=disabled/' /etc/selinux/config
    - shell: sleep 5 && shutdown -r now
      async: 1
      poll: 0
      args:
        creates: /usr/bin/pip-python
      ignore_errors: true
    - meta: clear_host_errors
    - pause:
        seconds: 30
# workaround: pip provider fails
    - shell: ln -s /usr/bin/pip /usr/bin/pip-python
      args:
        creates: /usr/bin/pip-python
# workaround: Create NFS share for glance
    - file:
        path: /srv/glance_nfs/cloud_devel
        state: directory
        recurse: yes
        mode: 0755
    - meta: clear_host_errors
  roles:
    - { role: ansible-role-nfs, nfs_exports: { "/srv/glance_nfs/cloud_devel *(rw,sync,no_root_squash)" } }


