---
# Puppetize API nodes.

- hosts: api
  become: true
  become_user: root
  pre_tasks:
    - name: Flush firewall rules for bootstrap - Puppetize will reinstate them
      shell: iptables -F
    - name: Use insecure in all /bin/openstack calls due to self-signed cert
      lineinfile:
        path: /bin/openstack
        insertafter: import\ sys
        line: "sys.argv.append('--insecure')"
      ignore_errors: True
    - name: Link pip-python to pip
      shell: ln -s /usr/bin/pip /usr/bin/pip-python
      args:
        creates: /usr/bin/pip-python
    - name: Add CA to CA bundle
      blockinfile:
        path: /etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt
        block: |
          {{ polte_ss_ca_cert }}
    - name: Add CA to CA bundle
      blockinfile:
        path: /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
        block: |
          {{ polte_ss_ca_cert }}
    - name: Add CAs
      lineinfile:
        path: "/etc/nova/{{ item }}.conf"
        insertafter: [keystone_authtoken]
        line: cafile=/etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt
        state: present
      with_items:
        - nova-api
        - glance-api
        - neutron
      ignore_errors: true
    - name: Restart services
      shell: "systemctl restart {{ item }}"
      with_items:
        - openstack-nova-api
        - openstack-glance-api
        - neutron-server
      ignore_errors: true
  roles:
    - { role: ansible-role-puppetize, ansible_fqdn: "{{inventory_hostname_short}}.openstacklocal" }
