---
# Install puppetmaster packages, puppetize puppetmaster.
# Install squid. Increase memory for puppet-server.

- name: Configure puppetmaster
  hosts: puppet
  tags: puppet
  become: true
  become_user: root
  roles:
    - role: ansible-role-puppetmaster
    - { role: ansible-role-squid, internal_net: "10.99.99.0/24" }
  post_tasks:
    - name: Workaround
      shell: iptables -F
    - name: Workaround - Modules may fall back to this dir
      shell: rm -Rf /etc/puppet/modules
    - name: Workaround - Modules may fall back to this dir
      shell: ln -s /etc/puppet/environments/{{puppet_environment}}/modules /etc/puppet/modules
      ignore_errors: True
