---
- hosts: compute
  become: true
  become_user: root
  pre_tasks:
#workaround: Compensate for missing Spacewalk
    - yum:
        name: "{{ item }}"
        state: present
      with_items:
        - centos-release-openstack-newton.noarch
        - unzip
        - ksh
        - libmcrypt
        - bind-utils
        - libtool-libs
    - unarchive:
        src: http://www.avagotech.com/docs-and-downloads/raid-controllers/raid-controllers-common-files/8-07-14_MegaCLI.zip
        dest: /tmp
        remote_src: yes
    - yum:
        name: /tmp/Linux/MegaCli-8.07.14-1.noarch.rpm
        state: present
  roles:
    - { role: ansible-role-puppetize, ansible_fqdn: "{{inventory_hostname_short}}.openstacklocal" }
