---
# Puppetize API nodes.

- hosts: api
  become: true
  become_user: root
  pre_tasks:
    - shell: iptables -F
  roles:
    - { role: ansible-role-puppetize, ansible_fqdn: "{{inventory_hostname_short}}.openstacklocal" }
