---
- hosts: compute
  become: true
  become_user: root
  pre_tasks:
#workaround: Compensate for missing Spacewalk
    - yum:
        name: "{{ item }}"
        state: present
      with_items:
#        - centos-release-openstack-newton.noarch
        - unzip
        - ksh
        - libmcrypt
        - bind-utils
        - libtool-libs
    - unarchive:
        src: http://www.avagotech.com/docs-and-downloads/raid-controllers/raid-controllers-common-files/8-07-14_MegaCLI.zip
        dest: /tmp
        remote_src: yes
    - yum:
        name: /tmp/Linux/MegaCli-8.07.14-1.noarch.rpm
        state: present
    - get_url:
        url: https://s3.amazonaws.com/opsview-agents/centos7/opsview-agent-5.4.1.172541017-1.ct7.x86_64.rpm
        dest: /tmp/opsview-agent-5.4.1.172541017-1.ct7.x86_64.rpm
        force: no
    - yum:
        name: /tmp/opsview-agent-5.4.1.172541017-1.ct7.x86_64.rpm
        state: present
#workaround: Nothing in puppet code seems to create these
    - shell: mkdir -p /var/log/nagios/.ssh
    - shell: touch /var/log/nagios/.ssh/authorized_keys
    - shell: chown nagios:nagios /var/log/nagios/.ssh/authorized_keys
  roles:
    - { role: ansible-role-puppetize, ansible_fqdn: "{{inventory_hostname_short}}.openstacklocal" }
