---
- hosts: compute
  become: true
  become_user: root
  pre_tasks:
#workaround: Compensate for missing Spacewalk
    - get_url:
        url: https://raw.githubusercontent.com/rdo-infra/rdo-release/newton-rdo/rdo-release.repo
        dest: /etc/yum.repos.d/rdo-release.repo
        mode: 0644
    - get_url:
        url: https://raw.githubusercontent.com/rdo-infra/rdo-release/newton-rdo/RPM-GPG-KEY-CentOS-SIG-Cloud
        dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-SIG-Cloud
        mode: 0644
#Pin to a specific repo in CentOS vault in order to get newton packages
    - replace:
        path: /etc/yum.repos.d/rdo-release.repo
        regexp: 'http://mirror.centos.org.*openstack-newton/'
        replace: 'http://vault.centos.org/centos/7.4.1708/cloud/x86_64/openstack-newton/'
    - replace:
        path: /etc/yum.repos.d/CentOS-OpenStack-newton.repo
        regexp: 'http://mirror.centos.org.*openstack-newton/'
        replace: 'http://vault.centos.org/centos/7.4.1708/cloud/x86_64/openstack-newton/'
      ignore_errors: true
    - yum:
        name: "{{ item }}"
        state: present
      with_items:
        - centos-release-openstack-newton.noarch
        - unzip
        - ksh
        - libmcrypt
        - bind-utils
        - libtool-libs
    - unarchive:
        src: http://www.avagotech.com/docs-and-downloads/raid-controllers/raid-controllers-common-files/8-07-14_MegaCLI.zip
        dest: /tmp
        remote_src: yes
    - yum:
        name: /tmp/Linux/MegaCli-8.07.14-1.noarch.rpm
        state: present
  roles:
    - { role: ansible-role-puppetize, ansible_fqdn: "{{inventory_hostname_short}}.openstacklocal" }
