---
- hosts: compute
  become: true
  become_user: root
  pre_tasks:
    - shell: yum -y install centos-release-openstack-newton.noarch
      ignore_errors: true
#HACK. TODO, figure out proper repos, keys etc.
    - shell: rpm -Uvh http://sarepos.cpanel.net/centos/7/noarch/MegaCli-8.07.14-1.el7.centos.noarch.rpm
      ignore_errors: true
    - shell: yum -y install /bin/ksh libmcrypt bind-utils libtool-libs
      ignore_errors: true
    - shell: rpm -Uvh https://github.com/amuraru/opsview-rpms/raw/master/centos/7/opsview-agent-4.5.4.473-1.ct7.x86_64.rpm
      ignore_errors: true
#TODO sort this out
    - shell: mkdir -p /var/log/nagios/.ssh
    - shell: chmod -R 700 /var/log/nagios
    - shell: touch /var/log/nagios/.ssh/authorized_keys
    - shell: chmod 777 /var/log/nagios/.ssh/authorized_keys
  roles:
    - { role: ansible-role-puppetize, ansible_fqdn: "{{inventory_hostname_short}}.openstacklocal" }
