---
# Install puppetmaster packages, puppetize puppetmaster.
# Install squid.

- name: Configure puppetmaster
  hosts: puppet
  tags: puppet
  become: true
  become_user: root
  roles:
    - { role: ansible-role-puppetmaster, puppetlabs_repo_url: "https://yum.puppetlabs.com/puppetlabs-release-pc1-el-7.noarch.rpm", yum_proxy: "http://puppet-node:3128" }
    - { role: ansible-role-squid, internal_net: "10.99.99.0/24" }
  post_tasks:
    - shell: iptables -F
    - shell: systemctl restart puppetserver
