---
- name: Configure puppetmaster
  hosts: puppet
  tags: puppet
  become: true
  become_user: root
  roles:
    - role: ansible-role-puppetmaster
    - { role: ansible-role-squid, internal_net: "10.99.99.0/24" }
  post_tasks:
    - shell: iptables -F
    - shell: systemctl restart puppetdb
    - shell: systemctl restart puppetmaster
