---
ansible_ssh_common_args: "-o ProxyCommand='ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -W %h:%p -q {{ vm_user_account }}@{{ hostvars['puppet-node']['ansible_ssh_host'] }}'"
ceph_origin: distro
ceph_stable_release: jewel
monitor_interface: eth0
public_network: "10.99.99.0/24"
osd_scenario: collocated
radosgw_interface: eth0
fsid: "12345678-90ab-cdef-1234-567890abcdef"
generate_fsid: false

openstack_config: true
openstack_glance_pool:
  name: glance-devel
  pg_num: "{{ osd_pool_default_pg_num }}"
  rule_name: ""
openstack_cinder_pool:
  name: cinder-devel
  pg_num: "{{ osd_pool_default_pg_num }}"
  rule_name: ""
openstack_nova_pool:
  name: vms-devel
  pg_num: "{{ osd_pool_default_pg_num }}"
  rule_name: ""
openstack_radosgw_pool:
  name: radosgw-devel
  pg_num: "{{ osd_pool_default_pg_num }}"
  rule_name: ""
openstack_pools:
  - "{{ openstack_glance_pool }}"
  - "{{ openstack_cinder_pool }}"
  - "{{ openstack_nova_pool }}"
  - "{{ openstack_radosgw_pool }}"
openstack_keys:
  - { name: client.glance-devel, key: "{{ vault_glance_devel_key }}", mon_cap: "allow r", osd_cap: "allow class-read object_prefix rbd_children, allow rwx pool={{ openstack_glance_pool.name }}", mode: "0600", acls: [] }
  - { name: client.cinder-devel, key: "{{ vault_cinder_devel_key }}", mon_cap: "allow r", osd_cap: "allow class-read object_prefix rbd_children, allow rwx pool={{ openstack_cinder_pool.name }}, allow rwx pool={{ openstack_nova_pool.name }}, allow rx pool={{ openstack_glance_pool.name }}", mode: "0600", acls: []  }
  - { name: client.nova-devel, key: "{{ vault_nova_devel_key }}", mon_cap: "allow r", osd_cap: "allow class-read object_prefix rbd_children, allow rwx pool={{ openstack_glance_pool.name }}, allow rwx pool={{ openstack_nova_pool.name }}, allow rwx pool={{ openstack_cinder_pool.name }}", mode: "0600", acls: [] }
  - { name: client.radosgw-devel, key: "{{ vault_radosgw_devel_key }}", mon_cap: "allow r", osd_cap: "allow class-read object_prefix rbd_children, allow rwx pool={{ openstack_radosgw_pool.name }}", mode: "0600", acls: [] }
